### ISSUE TITLE
comments doesn't load

### ISSUE THREAD

**Issue by ahmedflix25** [YePpHa/maia-yt#111]
Windows 10 April Update 
Firefox latest stable release

the comments doesn't load until i play the video

**Comment by tballas** [comment]
I've seen the same issue on Windows 10, Chrome 66 every time I open a video.

**Comment by dmack6464** [comment]
I also have the same issue on Windows 7 32 bit on the latest Chrome stable, but it also happens on an older version of Chromium on a different install of Windows 7 32 bit.

**Comment by ahmedflix25** [comment]
https://www.reddit.com/r/Windows10/comments/91jil3/youtube_page_load_is_5x_slower_in_firefox_and/

**Comment by ahmedflix25** [comment]
it was TamperMonkey 
TamperMonkey  doesn't play well with quantum
