### ISSUE TITLE
Better modularity and settings accessible outside youtube

### ISSUE THREAD

**Issue by mzso** [YePpHa/maia-yt#13]
Hi!

I think a huge issue with YTC is that when one crucial thing breaks you can't use the whole script because you can't disable only that part.
I suspect sometimes it's impossible to fully disable features, or stuff breaks regardless of enabled features, because of the injected script.
On the UI side (taking YTC as example) I imagine a practical solution would be to have all the categories and subcategories have checkboxes. And if they're unchecked all of the including features would be completely omitted.
(I'm hoping the "Only inject scripts into the page that is necessary for it to control the player and other essential things." milestone supports this)

Another thing is that I can't even try to disable features if the youtube page is sufficiently broken, because the ytc settings menu is only acessible from within the youtube page itself.

**Comment by YePpHa** [comment]
I completely understand. I've been considering this issue a lot and have decided on one way I want to implement features.

Features/modules will be isolated from the other modules and will only be able to access the exposed API from the core. The exposed API will include the registered players (https://github.com/YePpHa/maia-yt/blob/8785a3f9c98bf1a6228a707c4a43eed153ea244b/src/app/App.ts#L17) and some kind of settings API (haven't worked on this yet). However, I'm not sure if more should be made available, but that will be decided when the need arises.
The modules should also be disposable which means that they can be removed and revert any DOM modification back to the original state (CSS, buttons below the videos and etc.).
This will make it possible to completely disable modules that the user doesn't want or are broken (this should not happen, but it does).

As for the settings part I've yet to decide between the following options:
1. I will host a website where the settings can be accessed from and modified.
2. [Chrome/Firefox extension] Settings will be accessible from one of the extension's HTML pages.
3. I will take a 404 page from YouTube and replace all content with the settings.
4. I will do as I did with YouTube Center (not likely as it can make the settings inaccessible).

If you have any further comments, suggestions or improvements to what I've considered I will happily hear them.

Just a side note the `Only inject scripts into the page that is necessary for it to control the player and other essential things.` milestone is to improve the performance and doesn't make it modular. It also helps in keeping things less complicated as all the logic resides outside the page and makes it possible to use things from other domains without needing to think about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). As for YouTube Center everything was injected into the page and I had to open up a channel to a cross domain xhr method which made it very insecure to use on malicious pages (though YouTube is not malicious, but it was still a concern).

**Comment by mzso** [comment]
Great! Sounds like it'll substantially better than before.


[**@YePpHa**](https://github.com/YePpHa) commented on [2017. aug. 31. 14:01 CEST](https://github.com/YePpHa/maia-yt/issues/13#issuecomment-326274450 "2017-08-31T12:01:43Z - Replied by Github Reply Comments"):

> 1.  I will host a website where the settings can be accessed from and modified.
> 2.  [Chrome/Firefox extension] Settings will be accessible from one of the extension's HTML pages.
> 3.  I will take a 404 page from YouTube and replace all content with the settings.
> 4.  I will do as I did with YouTube Center (not likely as it can make the settings inaccessible).
> 
> If you have any further comments, suggestions or improvements to what I've considered I will happily hear them.

#1 sounds like to be rather fallible. If only this was available the settings could get inaccessible if the site is off line, or for some reason not accessible. #2-3 looks good to me. 

Oh, yeah. A button to reset to youtube/YTC default would be rather practical. (It's all or nothing in YTC) Or maybe styling could indicate which settings are changed and which are set to youtube's or YTC's default. (If they differ of course, but I expect in many cases they should, a script/addon that does nothing by default would be weird. :) )
