### ISSUE TITLE
Playback broken with youtube as of today

### ISSUE THREAD

**Issue by mzso** [YePpHa/maia-yt#136]
Hi!

Today I noticed that a bunch of times the video spinner would be spinning, and the player is unresponsive to my click after I start playback manually. I guess youtube changes broke the disable autoplay feature.
Refreshing the page doesn't help, I need to disable maia.

**Comment by YePpHa** [comment]
Please provide the following information:
- What browser are you using?
- What version of maia-yt are you using? (WebExtension, Userscript)
- What are you settings?

This will help a ton if I need to be able to debug it. I tried to test whether it broke for me too but wasn't able to reproduce the issue.

**Comment by mzso** [comment]
[**@YePpHa**](https://github.com/YePpHa) commented on [2019. febr. 3. 02:03 CET](https://github.com/YePpHa/maia-yt/issues/136#issuecomment-460013378 "2019-02-03T01:03:19Z - Replied by Github Reply Comments"):
> Please provide the following information:
> 
> *   What browser are you using?
> *   What version of maia-yt are you using? (WebExtension, Userscript)
> *   What are you settings?
> 
> This will help a ton if I need to be able to debug it. I tried to test whether it broke for me too but wasn't able to reproduce the issue.

I was using firefox with maia 0.2.1 (usersript). Updates from within FF doesn't work so I missed the latest version. I can't reproduce it now with 0.2.2. So I guess it might have been fixed. I'll check back if I experience the problem again.

**Comment by YePpHa** [comment]
Okay, in the meantime I will close this issue.
