### ISSUE TITLE
It looks like Maia breaks loading of stream and crashes the Waterfox content process.

### ISSUE THREAD

**Issue by mzso** [YePpHa/maia-yt#140]
Here's this specific video: https://www.youtube.com/watch?v=OyUPODpsQ0U
I couldn't load this while Maia was enabled, but as soon as I disabled it the stream started to work.

**Comment by YePpHa** [comment]
Are you using the userscript or webextension? I've tried installing Waterfox on Windows with the webextension version enabled. I was not able to test it with the video provided as it's not available anymore (at least for me). However, I tried with a random live video and it worked fine.

**Comment by mzso** [comment]
[**@YePpHa**](https://github.com/YePpHa) commented on [2019. febr. 19. 21:10 CET](https://github.com/YePpHa/maia-yt/issues/140#issuecomment-465291023 "2019-02-19T20:10:33Z - Replied by Github Reply Comments"):
> Are you using the userscript or webextension? I've tried installing Waterfox on Windows with the webextension version enabled. I was not able to test it with the video provided as it's not available anymore (at least for me). However, I tried with a random live video and it worked fine.

It was only this particular video and. I'll keep a lookout for more.
I use the userscript. The WE version doesn't seem to be usable. It's provided as a zip file, but even when I rename it to .xpi the browser claims it's corrupt.

**Comment by YePpHa** [comment]
Please do. As for the webextension. You just need to unpack it and open the manifest file. Not sure why opening the zip-file directly don't work.

**Comment by mzso** [comment]
Now I had trouble with this video: https://www.youtube.com/watch?v=AI3JzYCL3K0
But I doubt that it has anything to do with the video in question. I think something just brakes within Maia and persists for that video through page refreshes.

**Comment by YePpHa** [comment]
Strange. I'm not able to reproduce it at all. I tested on Waterfox (win10) with the userscript version enabled. I even disabled the autoplay (no buffering). I'm not able to break it at all.

**Comment by 0x5c** [comment]
Could it be cache/service-worker related? It happens on an "old" installation, but not on the new one.

**Comment by mzso** [comment]
[**@0x5c**](https://github.com/0x5c) commented on [2019. febr. 20. 19:29 CET](https://github.com/YePpHa/maia-yt/issues/140#issuecomment-465699010 "2019-02-20T18:29:30Z - Replied by Github Reply Comments"):
> Could it be cache/service-worker related? It happens on an "old" installation, but not on the new one.  
> Edit since I forgot to say it: clear the cache and unregister the service-worker(s) for youtube.

I don't know what it is but is getting common. Especially when I open multiple videos at one time.

**Comment by 0x5c** [comment]
Did you try to wipe the cache / unregister service-worker?

**Comment by mzso** [comment]
[**@0x5c**](https://github.com/0x5c) commented on [2019. febr. 27. 21:06 CET](https://github.com/YePpHa/maia-yt/issues/140#issuecomment-468010457 "2019-02-27T20:06:16Z - Replied by Github Reply Comments"):
> Did you try to wipe the cache / unregister service-worker?

How would I do that?

**Comment by 0x5c** [comment]
In would be in settings, of dev-tools for the site only

**Comment by mzso** [comment]
Didn't experience this for a long time now.
