### ISSUE TITLE
Implement auto-play prevention

### ISSUE THREAD

**Issue by YePpHa** [YePpHa/maia-yt#17]
Name | Type | Description
------- | ----- | ------------
enabled | boolean | whether to prevent auto-play.
mode | enum | the different modes of auto-play prevention: PAUSE and STOP.

Currently for the pause mode it's possible that a few milliseconds of the video will be played before it's paused. I might experiment with muting the volume or something along those lines or perhaps doing some hacky stuff to the HTML5 player.

**Comment by Y-T-G** [comment]
The auto-play prevention needs an option to prevent auto-play of Featured Feed Videos.

**Comment by 0x5c** [comment]
@Y-T-G 

> The auto-play prevention needs an option to prevent auto-play of Featured Feed Videos (Featured Video in a Channels's landing page).

You mean the "next-up" videos?

**Comment by Y-T-G** [comment]
I mean the one that plays when you visit a channel. Almost all popular channels have one.

**Comment by YePpHa** [comment]
@Y-T-G I've added support for featured channel videos in v0.1.3.

**Comment by Y-T-G** [comment]
@YePpHa 
Enabled the option but still not able to prevent the videos from auto playing.

**Comment by alindt** [comment]
@YePpHa, preventing auto-play of next video would be very useful, too.

**Comment by mzso** [comment]
[**@Y-T-G**](https://github.com/Y-T-G) commented on [2017. szept. 23. 18:45 CEST](https://github.com/YePpHa/maia-yt/issues/17#issuecomment-331649116 "2017-09-23T16:45:30Z - Replied by Github Reply Comments"):
> [@YePpHa](https://github.com/yeppha)  
> 
> Enabled the option but still not able to prevent the videos from auto playing.

It conflicts with YTC and I guess probably other scripts/addons too.

**Comment by Y-T-G** [comment]
@mzso 
Working now. Had to disable the first "Prevent auto play" option and then enable "Prevent channel auto play". Then, both of them started working. Weird.

**Comment by alindt** [comment]
Channel videos still autoplay in v0.1.3  ([x] Enable prevent channel auto-play)

**Comment by Y-T-G** [comment]
Featured channel videos auto play prevention option is buggy. Does not work most of the times. (Worked only once)

**Comment by YePpHa** [comment]
@alindt @Y-T-G Seems like I only did it for `/channel/` and not for `/user/`. I will fix this by looking at the `el` property instead.
