### ISSUE TITLE
Greenkeeper has been sold and canned.

### ISSUE THREAD

**Issue by nuenuewei** [YePpHa/maia-yt#183]
I noticed the project says it uses greenkeeper, however a company called snyk that offers a commercial version of the same service bought them and shut them down. It will stop working on June 3rd, and that also seems to be the deadline for transferring the account, if that's what you want to do.

**Comment by ahmedflix25** [comment]
this project is some what dead for a good time now so i think it doesn't really matter

**Comment by dmack6464** [comment]
Rest in pieces, Maia.

**Comment by nuenuewei** [comment]
Oh? That's a shame. The funny thing is, I'm still using youtube center and a lot of it still works.
