### ISSUE TITLE
Implement quality module

### ISSUE THREAD

**Issue by YePpHa** [YePpHa/maia-yt#23]
The quality module will set the quality of the video you're watching to your preferred quality.

I've added the following options:
- Enable/disable this module
- Preferred quality, which quality that's the target for your videos.
- Whether to go for the higher qualities or the lower qualities if the preferred quality is not available for the video you're watching.

I'm not sure if I've gotten all the needed features for this module implemented.

**Comment by alindt** [comment]
Choosing a predefined quality doesn't seem to work in combination with preventing autoplay (no buffering).

**Comment by YePpHa** [comment]
@alindt Thx for reporting the issue. I've found out why that happens and I've made a patch for it.
