### ISSUE TITLE
How do I build this ?

### ISSUE THREAD

**Issue by Y-T-G** [YePpHa/maia-yt#25]
Is it possible to build this?

**Comment by YePpHa** [comment]
Yes, it's possible to build it. However, it's currently only possible to build it as a userscript. I will add support for extensions later.

Before you're able to build this project you will need the following:
- [Node.js](https://nodejs.org/)
- [Yarn](https://yarnpkg.com/) (Optional)

You will then need to access your console (command prompt, powershell, bash, terminal) and go to the root of this project. After that you would need to enter the following commands:
```Bash
yarn install
yarn build:userscript
```

This will both install all dependencies and build the project as a userscript. The build userscript will then be placed in `dist/maia.user.js`.

**Comment by Y-T-G** [comment]
So I loaded the script in the Chrome extensions. I would like to know how do you set the default playback quality for YouTube videos.

**Comment by YePpHa** [comment]
got to https://www.youtube.com/settings/maia

**Comment by Y-T-G** [comment]
There is no way to save the settings or atleast I can't find one.

**Comment by YePpHa** [comment]
It saves them automatically at the moment.

**Comment by Y-T-G** [comment]
Doesn't seem to work for me. Resets after reloading.

**Comment by YePpHa** [comment]
Interesting, what browser are you using?

**Comment by Y-T-G** [comment]
Chrome.

**Comment by YePpHa** [comment]
Hmm, that's the same browser that I'm using to test it with. Do you use Tampermonkey or something else?

**Comment by Y-T-G** [comment]
No I don't.

**Comment by YePpHa** [comment]
Ahh so you're using it natively in Chrome then. That makes more sense why it doesn't work. I've only added storage that uses the GM_* API. That means GM_setValue and GM_getValue needs to be available.

I should probably add localStorage as an alternative if you're using userscripts.

**Comment by YePpHa** [comment]
I've added localStorage if GreaseMonkey API is not available. Travis should upload a new build [here](https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.1) soon. You can also build it yourself as I've commited the changes to master.
