### ISSUE TITLE
add option for dark theme mode

### ISSUE THREAD

**Issue by ahmedflix25** [YePpHa/maia-yt#56]
it would be nice of you to add an option that makes sure that the dark theme mode is on for the new design and add a dark theme for the old design.

**Comment by YePpHa** [comment]
Should be related to #28

**Comment by ahmedflix25** [comment]
The new design already had a dark mode https://imgur.com/a/5AU3r it just sometime turn itself off maybe it's a bug with youtube because i don't clear cookies or anything and it happened also with firefox chrome and edge so i wandered if you can add something to make sure it's always on if the user want to

**Comment by YePpHa** [comment]
Hmm. I will probably implement it under the [theming module](https://github.com/YePpHa/maia-yt/issues/28). As far as I know is it a class that's being set on the body or some other element.

**Comment by ahmedflix25** [comment]
thanks, keep up the good work
