### ISSUE TITLE
Preferred Quality does not enforce its setting.

### ISSUE THREAD

**Issue by Y-T-G** [YePpHa/maia-yt#73]
After setting the preferred quality through maia (say 720p), the first video that gets played on YouTube will play at "720p" but after that, the subsequent videos play at "Auto 720p" which YouTube scales according to my bandwidth.

**Comment by YePpHa** [comment]
@Y-T-G please check the latest version https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.10

**Comment by Y-T-G** [comment]
@YePpHa Still, same issue. First video after setting quality plays at at set quality. Subsequent videos play at Auto. Settings upto 360p sticks but 480p and above do not.

**Comment by YePpHa** [comment]
@Y-T-G Okay, I've done some more work and I might have fixed it. https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.12

**Comment by YePpHa** [comment]
There's still an issue with quality not being enforced.

**Comment by YePpHa** [comment]
This should very much fix the issue: https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.14

**Comment by Y-T-G** [comment]
@YTG Yes, it works now. Even Prefer Higher Quality setting works now. It never worked before.
