### ISSUE TITLE
low bandwidth issues

### ISSUE THREAD

**Issue by ahmedflix25** [YePpHa/maia-yt#76]
if the internet connection is slow the script doesn't enforce anything -i think because the player load before the script does- then after awhile from the video playing it enforces the quality and sometimes the player get jammed and doesn't play or buffer - i think that's when the script enforces the no buffering and no autoplay-

**Comment by 0x5c** [comment]
I think that I am experiencing similar issues with yt-center. If that's the case, the problem is deeply ingrained in the code.

**Comment by YePpHa** [comment]
Fix should be in https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.10. It seems like I forgot to change something when I made some changes in the core that handles the creation of a player.

**Comment by 0x5c** [comment]
Is the core from yt-player?

**Comment by YePpHa** [comment]
No, I've completely rewritten how it intercepts the player. There are some things that might be alike, but the system is much more simple and easier to handle. The core also acts like an API for the rest of Maia to make it easier to interact with YouTube.

I do plan to at some point to move the core of Maia to its own project where Maia will just depend on it, but that's still quite far into the future.

**Comment by ahmedflix25** [comment]
Nope still load and play the video without forcing anything

**Comment by ahmedflix25** [comment]
by the way i am on windows 10 FCU with firefox 57 64x with those Add-ons and Scripts
https://imgur.com/a/bJVi1

**Comment by YePpHa** [comment]
@ahmedflix25 It seems as though the `prevent auto-play (no buffering)` doesn't work anymore. I will need to look into what exactly the reason is for that.

**Comment by YePpHa** [comment]
@ahmedflix25 I found out that it wont set the quality correctly if it's 60fps. I will need to look into that as well.

**Comment by ahmedflix25** [comment]
well i set the quality to 360p so there isn't any 60 fps videos for me also after 3-5 second into the video the script enforce the quality even if it's already 360p and all the buffering are gone

**Comment by ahmedflix25** [comment]
i think it works now after the new update

**Comment by YePpHa** [comment]
@ahmedflix25 I've fixed some more stuff regarding quality. Please check it out: https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.12

**Comment by YePpHa** [comment]
Also continue the quality issue at #73 instead.
