### ISSUE TITLE
where the settings page?

### ISSUE THREAD

**Issue by Artlant** [YePpHa/maia-yt#86]
Sorry, but where is the settings page?

>Alpha milestone (current)
>.....
>**Simple settings**

I downloaded the latest release version _v0.1.15_
But in the version _webextension/maia.user.js_ they are not present.

Perhaps they are not implemented. But what does the extension do then? I did not see the possibilities.

Sorry if not right. But without a list of current features and settings. It's not clear what you release? Just the core expansion itself?

Regards 
Raingart

**Comment by kaser2010** [comment]
https://www.youtube.com/settings/maia

**Comment by Artlant** [comment]
@kaser2010 Thanks!
Maybe I'm blind, but it's worth redirecting when installing on this page or explicitly specify. Thanks again!
