### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by rayman89** [YePpHa/maia-yt#94]
I installed the latest release of the userscript but I cant notice it doing anything. From the front page it says it does loop the video but it did not do that. From the issues and version notes I can infer it currently does more than that but it still did nothing in my case. 

I'm using firefox 59 dev on win 7x64

This is what the js console log shows but I think it's not related to maia

https://hastebin.com/nujesatobo.sql

**Comment by YePpHa** [comment]
By default it does nothing, however, you can configure it at
https://www.youtube.com/settings/maia. If I remember correctly I only had
the loop feature as a test of the maia framework, but you can right click
on a video and tick the repeat item to repeat the video (provided by
YouTube).

**Comment by rayman89** [comment]
I see. Is there a plan to put an Icon to send you to that page? Otherwise how is the user supposed to know how to reach that url to enable the features?

**Comment by YePpHa** [comment]
It's on the Todo list, but I still have a ton of other things I need to
finish before that.

**Comment by rayman89** [comment]
BTW what does force auto navigation do? Also I can help you translate to Spanish when it's needed like I did with youtube center.

**Comment by YePpHa** [comment]
Force auto navigation is supposed to change the auto-play toggle in the recommended videos (shown in the image below), however, broken #88.
![image](https://user-images.githubusercontent.com/2348303/36753152-a4856812-1c05-11e8-9f37-5e85ac39c414.png)

I haven't yet made the underlining framework for translations yet and I will most definitely change everything related to that. So there's not anything that can be translated at the moment.
